### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by spectejb** [franck34/qjobs#5]
The license in the License file on github is MIT but there are references to the Beerware license in the code.  Can you confirm the correct license?  Thanks!

**Comment by franck34** [comment]
Hi @spectejb sorry for delay. MIT is the good one. I'll fix that in next release.

**Comment by spectejb** [comment]
Awesome.  Thanks, @franck34!

**Comment by franck34** [comment]
Pushing 1.2.0 in a few minutes without any changes except licence

**Comment by franck34** [comment]
1.2.0 pushed in npmjs registry, closing ticket.
